### PR TITLE
Don't completely fail on failing to retrieve file

### LINKED ISSUE #456: Don't completely fail on failing to retrieve file.
If you have a `Dockerfile` like this:

```Dockerfile
FROM ubuntu:latest

COPY * /tmp/
```

Then the whole parsing fails with `failed to retrieve "*": file does not exist` parsing error.

### PR DESCRIPTION
**Pull request by fkorotkov**
Fixes #456

### CODE REVIEW

File: pkg/parser/dockerfile.go [hunk 1]
```diff
@@ -135,7 +135,10 @@ func (p *Parser) calculateDockerfileHash(
 			newHash.Write(fileContents)
 			hashedAtLeastOneSource = true
 		}); err != nil {
-			return "", dockerfileNode.ParserError(err.Error())
+			p.registerIssuef(api.Issue_WARNING, dockerfileNode.Line, dockerfileNode.Column,
+				"%v %q: %v", ErrFailedToAnalyze, dockerfilePath, err)
+
+			return hex.EncodeToString(oldHash.Sum([]byte{})), nil
```
Comment (edigaryev) [inline pkg/parser/dockerfile.go:141]: No need to fail fast here: there can be other files that will hash successfully and `hashedAtLeastOneSource` will be `true`.

Comment (fkorotkov) [reply pkg/parser/dockerfile.go]: Fixed in b691e712f8c5de75c65e45187f72dfd8972709b8

**Review by edigaryev — APPROVED** [review]
